apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewvirt-web
  labels:
    app: viewvirt-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viewvirt-web
  template:
    metadata:
      labels:
        app: viewvirt-web
    spec:
      serviceAccountName: viewvirt
      securityContext:
        runAsNonRoot: true
      containers:
      - name: viewvirt-web
        image: quay.io/jkeam/viewvirt-web
        ports:
        - containerPort: 3000
        env:
        - name: API_BASE_URL
          value: "http://viewvirt-api:8080"
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 2
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: viewvirt-web
  name: viewvirt-web
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: viewvirt-web
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: viewvirt-web
spec:
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    name: viewvirt-web
