apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viewvirt

images:
- name: quay.io/jkeam/viewvirt-api
  digest: sha256:ea643d4dbd24d6067c17df83f057457ac4008324ca40d0097b162344122ead04
- name: quay.io/jkeam/viewvirt-web
  digest: sha256:48d60784a361c162e26fbe2bd567daa4d357326ac06dc11ee865e0cb780352e7

resources:
- namespace.yaml
- rbac.yaml
- deployment-api.yaml
- deployment-web.yaml
- console-link.yaml
