apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viewvirt

images:
- name: quay.io/jkeam/viewvirt-api
  digest: sha256:e28566aee773d813ff6a6394bcc619a5e6f4cb91adcc1219da8b1ea1ccf6d8fb
- name: quay.io/jkeam/viewvirt-web
  digest: sha256:48d60784a361c162e26fbe2bd567daa4d357326ac06dc11ee865e0cb780352e7

secretGenerator:
  - name: proxy-secret
    options:
      labels:
        app: viewvirt-web
    literals:
      - session_secret="VxfhQuztzp0b7J2RBPGynnHOmNTOVz0a/rq5tt8bf8s="

resources:
- namespace.yaml
- rbac.yaml
- deployment-api.yaml
- deployment-web.yaml
- console-link.yaml
