apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viewvirt

images:
- name: quay.io/jkeam/viewvirt-api
  digest: sha256:e28566aee773d813ff6a6394bcc619a5e6f4cb91adcc1219da8b1ea1ccf6d8fb
- name: quay.io/jkeam/viewvirt-web
  digest: sha256:597595ebefed925330288f7e8845c1c39cff21dcb832049d5431dc3ae92089bd

secretGenerator:
  - name: proxy-secret
    options:
      disableNameSuffixHash: true
      labels:
        app: viewvirt-web
    literals:
      - session_secret=whatever_you_want_here_doesnt_matter

resources:
- namespace.yaml
- rbac.yaml
- deployment-api.yaml
- deployment-web.yaml
- console-link.yaml
