---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewvirt-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewvirt

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewvirt-role-binding
subjects:
- kind: ServiceAccount
  name: viewvirt
roleRef:
  kind: Role
  name: viewvirt-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewvirt-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["kubevirt.io"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["*"]
  verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewvirt-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: viewvirt
roleRef:
  kind: ClusterRole
  name: viewvirt-cluster-role
  apiGroup: rbac.authorization.k8s.io
